//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRumbai
{
    using System;
    using System.Collections.Generic;
    
    public partial class keranjang
    {
        public int IdKeranjang { get; set; }
        public Nullable<int> IdMinuman { get; set; }
        public string namaMinuman { get; set; }
        public string ukuranMinuman { get; set; }
        public string topping { get; set; }
        public string jumlahMinuman { get; set; }
        public Nullable<int> hargaMinuman { get; set; }
    
        public virtual minuman minuman { get; set; }
    }
}
