//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRumbai
{
    using System;
    using System.Collections.Generic;
    
    public partial class ukuran
    {
        public int IdUkuran { get; set; }
        public string Ukuran1 { get; set; }
        public string HargaUkuran { get; set; }
    }
}
